# Kafka
kafka.bootstrap.servers=localhost:9092
kafka.topic=logs
kafka.group.id=log-consumer-group
kafka.max.poll.records=1000
kafka.poll.timeout.ms=1000

# Oracle
oracle.jdbc.url=jdbc:oracle:thin:@localhost:1521/ORCLPDB
oracle.username=LOG_USER
oracle.password=LOG_PASSWORD
oracle.pool.size=10

# Retry
consumer.retry.max.attempts=3
consumer.retry.initial.backoff.ms=500

# add to test insert when 1000
consumer.insert.batch.size=1000
consumer.insert.flush.timeout.ms=5000

# Staging
staging.max.pending=100000

# Processor
processor.batch.size=1000
processor.sleep.ms=1000

# Producer
producer.tps=1000
producer.client.id=log-producer
producer.acks=all
producer.linger.ms=100
producer.batch.size=32768
producer.buffer.memory=67108864

# Stats
stats.print.interval.ms=5000